apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: smtp-gateway
  labels:
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: smtp-gateway
    apps.tanzu.vmware.com/has-tests: "true"    
spec:
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: msgbroker-spring-smtp-gateway
  source:
    git:
      url: https://github.com/Mpluya/tap-spring-smtp-gateway
      ref:
        branch: main
    subPath: smtp-gateway
  params:
  - name: ports
    value:
    - port: 25
      containerPort: 1026
      name: smtp
